baseURL = 'https://magicyang876.github.io'
contentdir= "content"
layoutdir= "layouts"
publishdir= "magicyang876.github.io"
languageCode = 'en-us'
title = "James's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
canonifyurls = true
[taxonomies]
  category = "categories"
  tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2
[author]
  name = "James"
[params]
headTitle = "James Wang"
mainSections = ["posts"]

