baseURL = 'https://magicyang876.github.io'
contentdir= "content"
layoutdir= "layouts"
publishdir= "magicyang876.github.io"
languageCode = 'en-us'
title = "James's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
disablePathToLower = true
canonifyurls = true
[taxonomies]
  category = "categories"
  tag = "tags"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2
[params]
headTitle = "James Wang's Garden"
description = "知否知否，应是绿肥红瘦。"
mainSections = ["posts"]
favicon = "logo.ico"
custom_css = ["custom.css"]

extraCSSFiles = ["css/custom.css"]

[params.author.name]
name = "James Wang"

[author]
name = "James Wang"

[[params.socials1]]
name = "Contact(Telegram)"
link = "https://t.me/magicyang876"

[[params.socials]]
name = "Contact(X)"
link = "https://x.com/nameisacrazyjob"

[permalinks]
  posts = "/posts/:slug/"
  


